fix: connect wallet chain
bgd-labs/fe-shared pull request #32
Opened 2023-07-30 14:09 UTC by Argeare5

2023-07-31 08:49 UTC, Tima0203 approved these changes

2023-08-04 10:11 UTC, kyzia551 requested changes

2023-08-04 10:11 UTC, kyzia551 commented on src/web3/connectors/index.ts
> +  wcProjectId: string;
make optional

2023-08-04 10:11 UTC, kyzia551 commented on src/web3/adapters/EthereumAdapter.ts
> +        if (tx) {
add one general retry on all if's in this function

2023-09-11 08:52 UTC, kyzia551 approved these changes

2023-09-11 10:34 UTC, kyzia551 approved these changes

2023-09-11 10:34 UTC, merged